Repository szeyu/GoodFood, pull requests merged in 2025-01, with the labels that each got.

#57 User pref is sent to gemini for recipe search
  app/src/main/java/com/hmir/goodfood/ExtractIngredient.java
  app/src/main/java/com/hmir/goodfood/RecipeDetailActivity.java
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipe.java
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipeHelper.java
  app/src/main/res/layout/activity_recipe_detail.xml
Labels: enhancement, gemini

#59 recipe can be saved to fb
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipe.java
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipeHelper.java
Labels: database, gcp

#61 Searching now searches from each user's own favourite recipe
  app/src/main/java/com/hmir/goodfood/DatabaseHelper.java
  app/src/main/java/com/hmir/goodfood/DisplayActivity.java
  app/src/main/java/com/hmir/goodfood/Item.java
  app/src/main/java/com/hmir/goodfood/RecipeDetailActivity.java
  app/src/main/java/com/hmir/goodfood/ResultAdapter.java
  app/src/main/java/com/hmir/goodfood/SearchActivity.java
  app/src/main/java/com/hmir/goodfood/SearchAdapter.java
  app/src/main/java/com/hmir/goodfood/callbacks/OnRecipeAddedCallback.java
  app/src/main/java/com/hmir/goodfood/callbacks/OnRecipeDeletedCallback.java
  app/src/main/java/com/hmir/goodfood/callbacks/RecipeFetchCallback.java
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipe.java
  app/src/main/java/com/hmir/goodfood/utilities/FavouriteRecipeHelper.java
  app/src/main/java/com/hmir/goodfood/utilities/UserHelper.java
  app/src/main/res/layout/activity_display.xml
  app/src/main/res/layout/item_layout.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, database, gcp

#67 Display user info after login (name and profile picture from google account)
  app/build.gradle.kts
  app/src/main/java/com/hmir/goodfood/EditProfileFragment.java
  app/src/main/java/com/hmir/goodfood/HomePage.java
  app/src/main/java/com/hmir/goodfood/ProfilePage.java
  app/src/main/java/com/hmir/goodfood/WelcomePage.java
  app/src/main/java/com/hmir/goodfood/utilities/User.java
  app/src/main/java/com/hmir/goodfood/utilities/UserHelper.java
  app/src/main/res/drawable/baseline_photo_24.xml
  app/src/main/res/drawable/profile_circle.png
  app/src/main/res/layout/activity_home_page.xml
  app/src/main/res/layout/activity_profile_page.xml
  app/src/main/res/layout/activity_profile_page_functions.xml
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: enhancement, database, gcp, UX, UI

#68 done navigation to nutritions detail fragment after user click on meals image
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmir/goodfood/MealHistory.java
  app/src/main/java/com/hmir/goodfood/MealsAdapter.java
  app/src/main/java/com/hmir/goodfood/ThisMonthFragment.java
  app/src/main/java/com/hmir/goodfood/TodayFragment.java
  app/src/main/java/com/hmir/goodfood/utilities/UserHelper.java
  app/src/main/res/layout/activity_mealhistory.xml
Labels: enhancement, image, database, UX

#70 fix a huge bug where it cannot save the nutritional data to firebase
  app/src/main/java/com/hmir/goodfood/utilities/User.java
Labels: bug, gcp
